export const PRODUCTS = [
  {
    id: 1,
    slug: "run-grey-t-shirt",
    title: "Run Grey T-Shirt",
    image: "/assets/products/run-grey-t-shirt.jpg",
    stock: 10,
    price: 110,
  },
  {
    id: 2,
    slug: "run-blue-t-shirt",
    title: "Run Blue T-Shirt",
    image: "/assets/products/run-blue-t-shirt.jpg",
    stock: 10,
    price: 100,
  },
  {
    id: 3,
    slug: "run-red-t-shirt",
    title: "Run Red T-Shirt",
    image: "/assets/products/run-red-t-shirt.jpg",
    stock: 10,
    price: 100,
  },
  {
    id: 4,
    slug: "run-white-t-shirt",
    title: "Run White T-Shirt",
    image: "/assets/products/run-white-t-shirt.jpg",
    stock: 10,
    price: 110,
  },
  {
    id: 5,
    slug: "home-shorts",
    title: "Home Shorts",
    image: "/assets/products/home-shorts.jpg",
    stock: 10,
    price: 40,
  },
  {
    id: 6,
    slug: "icon-shorts",
    title: "Icon Shorts",
    image: "/assets/products/icon-shorts.jpg",
    stock: 10,
    price: 40,
  },
  {
    id: 7,
    slug: "icon-white-shorts",
    title: "Icon White Shorts",
    image: "/assets/products/icon-white-shorts.jpg",
    stock: 0,
    price: 40,
  },
  {
    id: 8,
    slug: "x-shorts",
    title: "X Shorts",
    image: "/assets/products/x-shorts.jpg",
    stock: 0,
    price: 75,
  },
];
